website:
  title: "Carla Castillo"
  
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
      - text: About
        href: about.qmd

    right:
      - icon: github
        href: https://github.com/carlaicastillo
      - icon: linkedin
        href: https://www.linkedin.com/in/carla-i-castillo-y